apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeusers
  template:
    metadata:
      labels:
        app: kubeusers
    spec:
      containers:
        - name: kubecontainer
          image: <username>/usercreator:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: URL de mongo
          imagePullPolicy: Always